name: CD - Main

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:
  build-and-push:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./SiteWebAPI
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/sitewebapi:latest
            ${{ secrets.DOCKERHUB_NAMESPACE }}/sitewebapi:${{ github.sha }}

      - name: Build & Push UI
        uses: docker/build-push-action@v6
        with:
          context: ./SiteWebUI
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/sitewebui:latest
            ${{ secrets.DOCKERHUB_NAMESPACE }}/sitewebui:${{ github.sha }}